name: reportsystem
version: 2.1
main: me.abdelrahmanmoharramdev.reportsystem.Reportsystem
author: Abdelrahman Moharram
description: A simple reporting system with GUI support for selecting players and report reasons

commands:
  report:
    description: Open GUI to report a player
    usage: /report
    permission: reportsystem.report

  reportlist:
    description: View recent reports in GUI
    usage: /reportlist
    permission: reportsystem.view

  reportreload:
    description: Reload the ReportSystem plugin config
    usage: /reportreload
    permission: reportsystem.reload

permissions:
  reportsystem.report:
    description: Allows a player to use /report
    default: true

  reportsystem.view:
    description: Allows a player to view reports using /reportlist
    default: op

  reportsystem.reload:
    description: Allows reloading of the ReportSystem config using /reportreload
    default: op

  reportsystem.notify:
    description: Receive notifications when a new report is submitted
    default: op
